### ISSUE TITLE
Swissmedic-Import 6.3.2019 fails

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/swissmedic-diff#3]
```
Plugin: ODDB::SwissmedicPlugin

Error: NoMethodError
Message: undefined method `to_date' for "unbegrenzt":String
Backtrace:
/var/www/oddb.org/vendor/ruby/2.5.0/gems/swissmedic-diff-0.2.6/lib/swissmedic-diff.rb:353:in `_comparable'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/swissmedic-diff-0.2.6/lib/swissmedic-diff.rb:295:in `block in rows_diff'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/swissmedic-diff-0.2.6/lib/swissmedic-diff.rb:292:in `each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/swissmedic-diff-0.2.6/lib/swissmedic-diff.rb:292:in `each_with_index'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/swissmedic-diff-0.2.6/lib/swissmedic-diff.rb:292:in `rows_diff'
/var/www/oddb.org/src/plugin/swissmedic.rb:776:in `rows_diff'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/swissmedic-diff-0.2.6/lib/swissmedic-diff.rb:209:in `block in diff'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/swissmedic-diff-0.2.6/lib/swissmedic-diff.rb:455:in `block in each_valid_row'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/worksheet.rb:23:in `block in each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/worksheet.rb:23:in `each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/worksheet.rb:23:in `each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/swissmedic-diff-0.2.6/lib/swissmedic-diff.rb:442:in `each_valid_row'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/swissmedic-diff-0.2.6/lib/swissmedic-diff.rb:183:in `diff'
/var/www/oddb.org/src/plugin/swissmedic.rb:339:in `update'
/var/www/oddb.org/src/util/updater.rb:421:in `block in update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:526:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:419:in `update_swissmedic'
jobs/import_swissmedic:14:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_swissmedic:12:in `<module:Util>'
jobs/import_swissmedic:11:in `<module:ODDB>'
jobs/import_swissmedic:10:in `<main>'
```

**Comment by ngiger** [comment]
Anstelle eines Datums für die Gültigkeitsdauer der Zulassung (bisher maximal 5 Jahre in die Zukunft) steht seit Februar in einigen "unbegrenzt". Dieser Fall wird nicht abgehandelt (auch in oddb.org nicht).
Wenn ich unbegrenzt durch ein Datum z.B. 31.12.2099 ersetzt muss ich zwar keinen Code in oddb.org ändern, aber dies ist ein hässlicher Hack. Oder er brauchte dort einen Hack um 31.12.2099 durch "unbegrenzt" zu ersetzen.
Muss mir überlegen, ob ich DateTime (oder Date) class um ein "unbegrenzt" erweitern könnte, oder ob sowas irgendwo schon implementiert wurde. Dies würde jedoch neben Anpassungen in swissmedic-diff auch solche in oddb.org nach sich ziehen.

**Comment by zdavatz** [comment]
Am besten wäre den Wert so zu übernehmen, wie er in der Tabelle steht: `unbegrenzt` d.h. anstelle von einem Datum einfach `unbegrenzt` anzeigen.

Ev. kannst Du es einfach mit einem String reinschreiben.

**Comment by zdavatz** [comment]
Oder was noch einfacher ist: Falls _unbegrenzt_ erscheint, einfach das Feld leer lassen und gar nicht reinschreiben. Das ist wohl die beste Lösung.

**Comment by ngiger** [comment]
Die zweite Lösung, das Feld leer lassen finde ich besser, das ist nämlich möglich. Ein String ist ein andere Klasse als Date.
Mein Import-daily brauchte zuviel Memory. Muss ihn nochmals starten lassen.

**Comment by zdavatz** [comment]
Ja, unbegrenzt ist auch nicht wirklich eine _Datum-Information_. Lassen wir das Feld einfach leer.

**Comment by ngiger** [comment]
oddb.org hat jeweils die ganze Sequenz/Packung gespeichert, wenn das expiration_date-Feld leer war. Deshalb muss das plugin/swissmedic.rb angepasst werden.

**Comment by zdavatz** [comment]
also nicht swissmedic-diff?

**Comment by ngiger** [comment]
Es braucht einen Patch hier in swissmedic-diff und einen Patch in oddb.org. Import-Daily ist bei mir jetzt über die Fehlerstelle hinweggekommen (musste jeweils 20min warten) aber nochnicht durch.
